spring.application.name=ecart
spring.datasource.url=jdbc:sqlite:./data/ecart.db
spring.datasource.driver-class-name=org.sqlite.JDBC
management.endpoints.web.exposure.include=health,info
server.error.include-stacktrace=never
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
ecart.discount.default-nth-order=3
ecart.discount.default-percent=10
ecart.admin.allowed-roles=ADMIN
